events {}

http {
    server {
        listen 80;

        # FRONTEND
        location / {
            proxy_pass http://vue-app:5173;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # BACKEND API
        location /api/ {
            proxy_pass http://backend-app:8000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
